micronaut:
  application:
    name: mnStockBroker
  security:
    enabled: false
  server:
    port: 8080
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from Service!"
  config:
    greeting:
      de: "Hallo"
      en: "Hello"
